CREATE SEQUENCE POST_NUMBER_SEQ START WITH 1 CACHE 20;

CREATE TABLE POST
(
    USER_ID NVARCHAR2(20) NOT NULL,
    PASSWORD NVARCHAR2(64) NOT NULL,
    TITLE NVARCHAR2(50) NOT NULL,
    CONTENT NCLOB NOT NULL,
    POST_DATE DATE NOT NULL,
    MODIFY_DATE DATE NOT NULL,
    HASHTAGS NVARCHAR2(50),
    "LIKE" NUMBER DEFAULT 0,
    UNLIKE NUMBER DEFAULT 0,
    HIT NUMBER DEFAULT 0,
    POST_NUMBER NUMBER NOT NULL
);

CREATE TABLE "COMMENT"
(
    USER_ID NVARCHAR2(20) NOT NULL,
    PASSWORD NVARCHAR2(64) NOT NULL,
    CONTENT NCLOB NOT NULL,
    COMMENT_DATE DATE NOT NULL,
    POST_NUMBER NUMBER NOT NULL
);
